### ISSUE TITLE
Application fails to start

### ISSUE THREAD

**Issue by knippers** [bububa/MongoHub-Mac#1]
It reports the following error: 

Process:         MongoHub [80077]
Path:            /Downloads/2010/May-10/MongoHub.app/Contents/MacOS/MongoHub
Identifier:      com.thepeppersstudio.MongoHub
...
Date/Time:       2010-05-02 13:27:34.438 +0200
OS Version:      Mac OS X 10.6.3 (10D573)

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: libboost_system.dylib
  Referenced from: /Downloads/2010/May-10/MongoHub.app/Contents/MacOS/MongoHub
  Reason: image not found

**Comment by knippers** [comment]
I fixed it by building the libboost libraries and setting the DYLD_LIBRARY_PATH to the boost_1_42_0/stage/lib path and start MongoHub from the command line: ./MongoHub.app/Contents/MacOS/MongoHub

**Comment by dennisreimann** [comment]
For me it doesn't work because the SSHTunnel.framework is missing, how do I resolve this?

**Comment by bububa** [comment]
@knippers
thank you very much:)
You can also try to del the dylib of boost and compile it.

**Comment by cps** [comment]
It's fixed for me in the 2.0.5 Beta release.
Thank you.

**Comment by dennisreimann** [comment]
Ok, now it works for me too - thanks!

**Comment by bububa** [comment]
@cps @dbloete thankx for yours reports:)

**Comment by knippers** [comment]
The 2010-05-05 Download works for me too now out of the box (as in double click app no command prompt needed anymore). 
Setting this issue to closed (if you don't mind).
