### ISSUE TITLE
2.0.9 quit unexpectedly after upgrade

### ISSUE THREAD

**Issue by kriswill** [bububa/MongoHub-Mac#12]
After allowing the upgrade from 2.0.8 to 2.0.9, I lose all settings (pre-existing connections are gone).

full report dump at http://gist.github.com/418824

**Comment by kriswill** [comment]
re-openning Mongohub results in this error:  

The managed object model version used to open the persistent store is incompatible with the one that was used to create the persistent store.

followed by this error:

Failed to initialize the store

**Comment by bububa** [comment]
In order to support mongohq, I changed the coredata structure. So you need to delete the old database in ~/Library/Application\ Support/MongoHub directory manually before you install the new version.

**Comment by kriswill** [comment]
yup that worked.  But I had to re-configure all of my connections.  Maybe do a transform in the future to upgrade to any new formats?

**Comment by bububa** [comment]
:) I'll do a transform in later version.
