### ISSUE TITLE
New Feature:  Use .ssh/id_rsa to proxy/pipe for mongodb

### ISSUE THREAD

**Issue by kriswill** [bububa/MongoHub-Mac#13]
The current SSH feature only supports user_name@host with password.  If we could have it use a specific private key, where the corresponding pub key is in the .ssh/authorized_keys, it would be far more useful, in that we wouldn't need to store potentially sensitive passwords in the ~/Library/Application Support/MongoHub/storedata.

When I say tunnel I mean the equivalent of using:

> ssh -L 8888:localhost:27017 username@hostname.tld

this would configure local port 8888 to tunnel the remote's [hostname.tld] localhost port 27017

or if you have ssh access to a machine that can then connect to the mongo

> ssh -L 27017:othermachine:27017 username@host

would tunnel local 27017 thru host which would forward othermachine's 27107

**Comment by kriswill** [comment]
right now I have to console to setup the ssh tunnel, and configure the connection to connect to localhost:port for remote mongodb.  I'm simply asking for MongoHub to do this setup automatically, using my rsa key.

**Comment by bububa** [comment]
good suggestion, I'll add this in feature request list.
Thankx

**Comment by mtowers** [comment]
I'll second this one.  Though I would add that it would be nice to be able to specify the exact location and name of the private key to use. (e.g. ssh -i /path/to/my/key.pem ...)

This should make it possible to use MongoHub to manage mongodb running on an Amazon EC2 instance, wherein private keys are typically stored in ~/.ec2/.

**Comment by darscan** [comment]
This would be very useful - especially if the host only supports key authentication.

**Comment by milesw** [comment]
You should be able to configure SSH to always use that key for your EC2 hosts. See here: http://superuser.com/questions/88359/mount-ec2-instance-via-ssh-on-mac-os-x

**Comment by mtowers** [comment]
Thanks for the ssh config tip!  Have you been able to get that to work with mongohub without setting up a tunnel manually?

**Comment by milesw** [comment]
Nope, haven't gotten it to work. Would be nice, but setting up the tunnel manually isn't much of a hassle.

**Comment by bububa** [comment]
Added this feature in 2.3.2

**Comment by kriswill** [comment]
Woot, Thanks!

**Comment by darscan** [comment]
Awesome, thanks!

**Comment by vgoklani** [comment]
not sure how this works, what do I have to enter into the MongoHub preferences to connect to my MongoDB remote instance on EC2? I can open an SSH tunnel, specify the post via localhost, and then tell MongoHub to connect to that port. Is it possible to connect directly without opening a separate SSH tunnel in the command line?

**Comment by santimacia** [comment]
+1 I can't get this work with mongohub, i stored the key in .ec2 and created the .ssh/config
