### ISSUE TITLE
Getting an error connecting to Mongo 1.42

### ISSUE THREAD

**Issue by ghost** [bububa/MongoHub-Mac#14]
The managed object model version used to open the persistent store is incompatible with the one that was used to create the persistent store.

getting this error

**Comment by bububa** [comment]
*If you are using the version less than 2.0.8, you need to remove ~/Library/Application\ Support/MongoHub directory and 
restart the new version.

**Comment by dmitryame** [comment]
I'm using the latest 2.1.0 and it's still happening to me, should I remove the ~/Library/Application\ Support/MongoHub anyways?

**Comment by dmitryame** [comment]
well, that did the trick, it's just a bit misleading about the version number, seems to happen even in the latest and greatest
