### ISSUE TITLE
Merge Query window into Connection?

### ISSUE THREAD

**Issue by ghost** [bububa/MongoHub-Mac#16]
Right now it takes too many clicks to see data.

Just a personal preference: it would be nice if the "Query" window was a pane of the main "Connection" view. Juggling three windows gets unwieldy.  Ideally one could have several Query panrs open in tabs.

If this was implemented, I'd think that "Query" should be the default pane, rather than Database or Connection stats.

 It would also be nice if double-clicking the Collection on the left opened up the Query view.

**Comment by bububa** [comment]
Thanks for your suggest. I considered it at the beginning of software design. But I found it is much more complicate to implement than to open a query window. I probably will change the view in future but not soon.
