### ISSUE TITLE
Array values not displayed

### ISSUE THREAD

**Issue by ghost** [bububa/MongoHub-Mac#18]
I have a document with an array of ObjectIds (stored as strings) to contain a has-many association. The association works in code, indicating that the array is correctly populated, but in MongoHub the array values display as blank:

http://skitch.com/slowernet/dek44/

**Comment by bububa** [comment]
Yes, this is a bug in - (NSMutableArray *) bsonArrayWrapper:(mongo::BSONObj)retval function. I've fixed this in the github repository but didn't compile it.
It will be fixed in the next coming version.
