### ISSUE TITLE
resizing the query/find window does not move the expand/collapse buttons

### ISSUE THREAD

**Issue by perezd** [bububa/MongoHub-Mac#23]
They stick in the middle of the screen, see screenshot: http://grab.by/5wid

**Comment by cloudbring** [comment]
This is happening for me as well.

**Comment by masopmac** [comment]
This is an issue with the "Autosizing" settings on the expand and collapse buttons, which are part of the QueryWindow.xib file. If you get the source and are able to link the necessary frameworks you can address this using "interface builder".

**Comment by kmatt** [comment]
Confirmed masopmac's suggestion. By setting the button autosizing location to the lower right corner from the upper left seems to resolve the issue.

**Comment by bububa** [comment]
fixed in the next version.
