### ISSUE TITLE
Mysql import of "date" type fields get imported with 1970 date

### ISSUE THREAD

**Issue by masopmac** [bububa/MongoHub-Mac#25]
Issue: When using the "Import(MySQL)" feature of mongohub , "date" field types get imported with a 1970 style date. 

Example: 
Mysql value = 2009-11-11
Value in mongodb after import = 1970-01-15 07:25:19 -0600

For "datetime" field types the import appears to work correctly. 

I'm going to be using this to migrate 22,054 records to mongodb. My test import took around 1 minute 4 seconds, not too bad. This tool is going to save me a lot of time on the import side of things. Thanks for the good work!

System Configuration:

MongoDB version 1.4.4 running on OS-X 10.6.4
Mysql version 5.1.37 running on OS-X 10.6.4

**Comment by anlek** [comment]
If anyone is looking for a tool to migrate your data from MySql to MongoDB, give this tool a try: http://github.com/anlek/mongify
