### ISSUE TITLE
MongoHub detecting wrong type for references_many and referenced_in ?

### ISSUE THREAD

**Issue by krzkrzkrz** [bububa/MongoHub-Mac#27]
Ive got a user and photo document. I am using MongoId to set the associations.

User model has:
references_many :songs

Photo model has:
referenced_in :user

When a record is created for photo. everything saves except, user_id is blank and the type is indicated as "String"

In mongo console, if i do:
db.songs.find({ 'title': 'foobar' }), it returns:

{ "_id" : ObjectId("4cd298ba72357e267200000c"), "description" : "adsf", "title" : "foobar", "stream_type" : "full", "is_downloadable" : "0", "user_id" : ObjectId("4cd1505f72357e287b000001"), "media_filename" : "02_-_driftwood.mp3" }

It is clear that MongoHub is not reporting the right data type for referential associations.

This could be a bug.

**Comment by krzkrzkrz** [comment]
To verify. I check the type of user_id by doing: db.songs.find({ user_id : { $type : 7 }})

I get:

{ "_id" : ObjectId("4cd29b9c72357e2672000018"), "description" : "asdf", "title" : "foobar", "stream_type" : "full", "is_downloadable" : "0", "user_id" : ObjectId("4cd1505f72357e287b000001")", "media_filename" : "02_-_driftwood.mp3" }

It proves that user_id is of ObjectId type, but why is MongoHub saying that is a String type?

**Comment by bajohns** [comment]
I can confirm this error this occurs using MongoHub 2.1 and Mongoid 2.0.0.beta.20.  

Let me know if you want me to test.

**Comment by bububa** [comment]
fixed in the next coming version.
