### ISSUE TITLE
How to query by ObjectId type?

### ISSUE THREAD

**Issue by Shopperhive** [bububa/MongoHub-Mac#33]
Hi guys,

I would like to be able to query by ObjectId as this is what MongoHub is returing for _id. How to do this, something like {"_id":"4d1b4687a6d5437619000000"} is not working??

cheers,
/Marcin

**Comment by bububa** [comment]
You should use {"_id": ObjectId("4d1b4687a6d5437619000000")}

**Comment by Shopperhive** [comment]
Not working like that, getting: Object value expected for key: _id, my Mongohub version is: 48

**Comment by bububa** [comment]
fixed in source code, the new version will be released in the next week.

**Comment by Shopperhive** [comment]
great, thanks
