### ISSUE TITLE
App crashes on "select all" query

### ISSUE THREAD

**Issue by igrigorik** [bububa/MongoHub-Mac#34]
Running 2.3.0[61], reliably getting the following result:

Application Specific Information:
abort() called
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSCFDictionary setObject:forKey:]: attempt to insert nil value (key: raw)'
**\* Call stack at first throw:
(
    0   CoreFoundation                      0x00007fff87a0e7b4 __exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x00007fff86af90f3 objc_exception_throw + 45
    2   CoreFoundation                      0x00007fff87a0e5d7 +[NSException raise:format:arguments:] + 103
    3   CoreFoundation                      0x00007fff87a0e564 +[NSException raise:format:] + 148
    4   Foundation                          0x00007fff8199fc86 -[NSCFDictionary setObject:forKey:] + 227
    5   MongoHub                            0x000000010002c6f5 -[MongoDB findInDB:collection:user:password:critical:fields:skip:limit:sort:] + 3425
    6   MongoHub                            0x0000000100033b76 -[QueryWindowController doFindQuery] + 525

**Comment by bububa** [comment]
This error looks strange. Can you show me the demo of your data?
