### ISSUE TITLE
Opening on Mac

### ISSUE THREAD

**Issue by scottmessinger** [bububa/MongoHub-Mac#39]
Hi,

When I open the app, I get the follow dialog box:
Persistent store migration failed, missing source managed object model.

After I click "okay" I get another dialog box:
Failed to initialize the store

Any ideas why this is happening?

Thanks,
Scott

**Comment by bububa** [comment]
Maybe you use a very old version of mongohub. please remove ~/Library/Application\ Support/MongoHub/ folder and install the latest version.

**Comment by scottmessinger** [comment]
Thanks! That solved the problem!

**Comment by jmgamboa** [comment]
that was great. worked for me too!
