### ISSUE TITLE
Website problems

### ISSUE THREAD

**Issue by afeld** [bububa/MongoHub-Mac#40]
Hi-
When trying to access http://mongohub.todayclose.com/, I am getting a strange error:

```
Your client does not have permission to get URL / from this server.
```

I'm not behind a firewall, nor do I hav a static IP or anything strange.  Had to download MongoHub from Apple!

**Comment by bububa** [comment]
http://mongohub.todayclose.com/ is hosted on google appengine. There are some unknown problems with google appengine. Need to wait for until google fixed this problem.

But you can still download the lastest version from github download page. This is the link for the software:
https://github.com/downloads/bububa/MongoHub-Mac/MongoHub.zip

By the way, don't download from apple's website. It's not the latest version of mongohub. They don't update the download page anymore.
