### ISSUE TITLE
can't compile in xcode4

### ISSUE THREAD

**Issue by rjyo** [bububa/MongoHub-Mac#47]
**error:**
Unable to resolve Interface Builder plug-in dependency for "MainMenu.xib". This document requires the com.brandonwalkin.BWToolkit Interface Builder 3 plug-in. Consider using Interface Builder 3 to edit this document.

**Comment by bububa** [comment]
Sorry, I don't have xcode4:( I'll com.brandonwalkin.BWToolkit plugin in the next version.
