### ISSUE TITLE
Won't run on 32bit CPU

### ISSUE THREAD

**Issue by mjsuhonos** [bububa/MongoHub-Mac#49]
"You can't open the application MongoHub because it's not supported on this type of Mac"

I'm assuming this is because MongoHub is built for 64-bit CPUs and I am running a Core Duo Macbook.

Any chance you could include 32-bit in the build target for the next release?  Thanks.

**Comment by bububa** [comment]
Sorry, I don't have old Macbook to compile it in 32-bit. I'll try if I have additional computer.

**Comment by mjsuhonos** [comment]
Thanks for the response. I didn't realize that building for 32-bit required actual older hardware -- I thought it was just a compile-time flag or similar.

I'm sure there's not that much demand, and as of 10.7 it will be moot anyway. No worries.

**Comment by bububa** [comment]
The problem is need to compile libmongoclient.a in 32bit. But on my laptop it is 64bit
