### ISSUE TITLE
mongoHQ support

### ISSUE THREAD

**Issue by iaincarsberg** [bububa/MongoHub-Mac#5]
Hey, being able to connect to mongoHQ would be handy, they use "mongo server.mongohq.com:27020/database -u <user> -p <pass>" as the connection path.

**Comment by bububa** [comment]
supported in the new version(2.0.9)

**Comment by iaincarsberg** [comment]
ah cool, thanks for the heads up

**Comment by jamischarles** [comment]
Any docs or FAQs for how to do this? I'm trying to use the interface to connect but keep getting errors.
