### ISSUE TITLE
Does not work in OS X Lion at all

### ISSUE THREAD

**Issue by thevinci** [bububa/MongoHub-Mac#58]
Program starts but when I attempt to connect to database via SSH connection it crashes.

**Comment by respectTheCode** [comment]
I am having the same problem

**Comment by erikcw** [comment]
I'm also having this problem when trying to use an SSH tunnel.

**Comment by lodog** [comment]
same here... it would be great to get a resolution to this. I love this tool but it's useless now that I've upgraded.

**Comment by jeromelebel** [comment]
I'm working a branch of MongoHub. My goals are : easy to compile, no crash and keep all the features. I work a little on no crashes. I still work a lot on easy to compile (so far, you still have to install mongo using macports), and I have a lot of progress to do on keep all the features...

http://github.com/fotonauts/MongoHub-Mac

**Comment by respectTheCode** [comment]
Thanks @jeromelebel.

**Comment by lodog** [comment]
How do I get and install your version?

Thanks,
Lorin
