### ISSUE TITLE
MongoHub not supported on macbook pro intel 32bit?

### ISSUE THREAD

**Issue by AndersRasmussen** [bububa/MongoHub-Mac#6]
When I try to launch MongoHub on my MacbookPro intel 32bit running Snow Leopard i popups with "You can't open the application MongoHub because it is not supported on this type of Mac."

**Comment by hampelm** [comment]
Seconded -- I have the same issue.

**Comment by jhancock** [comment]
some problem with first-gen iMac Core Duo w/ Leopard (10.5.8).  This seems like an arbitrary limitation...can someone shine some light on this?

**Comment by bskelton** [comment]
Same issue here. 

32-bit Snow Leopard

**Comment by jimsynz** [comment]
I have the same issue with 10.6.4 on Core Duo MacBook Pro.

**Comment by jhannah** [comment]
Same thing. 10.6.4 2GHz Intel Core Duo MacBook.

**Comment by LNGi** [comment]
Same issue. I use a 32-bit Snow Leopard

**Comment by cdulecki** [comment]
It appears that Mongohub is a 64 bit binary, which means it can only run on 64 bit machines.  It simply won't work on older hardware.  It would be nice if that were in the requirements - all the requirements say are 10.6 or higher.

**Comment by jimsynz** [comment]
I tried really hard to get it to compile on my old 32 bit MBP, but was unable to get the build environment set up the same as @bububa's one.

**Comment by ciferkey** [comment]
What are the odds that a 32bit version could be made? I tried to compile it on xcode, but was unable to...

**Comment by campeterson** [comment]
+1 with 32 bit Snow Leopard issue.

**Comment by bububa** [comment]
MongoHub is compiled under SL 64bit environment. If you want to build on your own machine, please install boost(boost.org) and compile it as 32bit first then compile mongodb c++ driver.
If you can't build the source code please send me the compile error logs.

**Comment by bububa** [comment]
2.2.0 probably works on any 10.6 system.

**Comment by iandennismiller** [comment]
MongoHub won't compile on i386 because synthesized ivars are not supported.  The solution is to specify a "backing" variable for all ivars.  Then, it might compile under i386...

**Comment by kof** [comment]
same thing, please fix it :)

**Comment by zutherb** [comment]
same thing .... is it possible to compile it myself
