### ISSUE TITLE
UI problem when document contains an array

### ISSUE THREAD

**Issue by antunderwood** [bububa/MongoHub-Mac#7]
When clicking on the drop down arrow at an Array type within a document, the window freezes and displays none of the items in the array. I cannot even close the window. However the app is still alive and I can open other windows.

**Comment by ansky** [comment]
I see the same behavior.   When running from the console, the error is:
   MongoHub[4299:903] -[NSCFArray objectForKey:]: unrecognized selector sent to instance 0x1005a5e50

**Comment by bububa** [comment]
probably fixed in the new version(2.0.9), please check.

**Comment by ansky** [comment]
Yup, fixed.  Thanks!

**Comment by bububa** [comment]
ok

**Comment by antunderwood** [comment]
Yep worked for me - although it did complain with this error message "The managed object model version used to open the persistent store is incompatible with the one that was used to create the persistent store." I had to delete the storedata from the Application Support folder and recreate my connections
