### ISSUE TITLE
Floating Remove button

### ISSUE THREAD

**Issue by ghost** [bububa/MongoHub-Mac#78]
Happens on Mac OS 10.6.8
Steps to produce:
1/ Open query windows
2/ Look at the bottom where sit Remove, Expand, Collapse buttons
3/ Drag and expand the window
Result: Remove button becomes floating and doesn't align with the other two buttons.

**Comment by wheelsandcogs** [comment]
I just came here to report this, looks like you beat me to it.

**Comment by wheelsandcogs** [comment]
Actually it's a dupe of #52

**Comment by ghost** [comment]
Oh ya, so sorry, I didn't check carefully before I posted this, seems like this report should be removed
