### ISSUE TITLE
Clicking on sort box crashes application

### ISSUE THREAD

**Issue by ericnakagawa** [bububa/MongoHub-Mac#80]
![Example](https://img.skitch.com/20120829-tpe9b5uk8c382mp83qemdr3np8.jpg)

**Comment by ericnakagawa** [comment]
I'm on Mountain Lion OSX 10.8.1

**Comment by ericnakagawa** [comment]
To reproduce, click on search box then begin typing. Application should crash.

**Comment by joe1chen** [comment]
@ericnakagawa I just realized that this project seems to have been abandoned.  However, https://github.com/fotonauts/MongoHub-Mac seems to have taken over active development.

**Comment by ericnakagawa** [comment]
Thanks for the heads up @joe1chen ! This is much further along then I expected! ^5
